sudo: false

language: go

go:
  - 'tip'

script:
 - go vet ./...
 - go test -v ./...
 - make setup

notifications:
  email: false

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "tip" ]; then test -n "$TRAVIS_TAG" && script/release.sh; fi
